"""baseline: schema atual do Supabase

Revision ID: a742e49834c9
Revises: 
Create Date: 2026-08-10 15:08:53.271595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a742e49834c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_artists_artist', table_name='event_artists')
    op.drop_table('event_artists')
    op.drop_table('artists')
    op.drop_table('users')
    op.alter_column('events', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_events_date', table_name='events')
    op.drop_constraint('uq_event', 'events', type_='unique')
    op.alter_column('scraper_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_event_status', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_status_event', table_name='user_event_status')
    op.drop_index('idx_status_user', table_name='user_event_status')
    op.drop_constraint('uq_user_event', 'user_event_status', type_='unique')
    op.alter_column('venues', 'state',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('venues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_venues_city', table_name='venues')
    op.drop_constraint('uq_venue_name_city', 'venues', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_venue_name_city', 'venues', ['name', 'city'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_venues_city', 'venues', ['city'], unique=False)
    op.alter_column('venues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('venues', 'state',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)
    op.create_unique_constraint('uq_user_event', 'user_event_status', ['user_id', 'event_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_status_user', 'user_event_status', ['user_id'], unique=False)
    op.create_index('idx_status_event', 'user_event_status', ['event_id'], unique=False)
    op.alter_column('user_event_status', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scraper_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_event', 'events', ['name', 'event_date', 'venue_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_events_date', 'events', ['event_date'], unique=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("email::text ~* '^[^@]+@[^@]+\\.[^@]+$'::text", name='chk_email_format'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('artists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='artists_pkey'),
    sa.UniqueConstraint('name', name='artists_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('event_artists',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='event_artists_artist_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_artists_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'artist_id', name='event_artists_pkey')
    )
    op.create_index('idx_event_artists_artist', 'event_artists', ['artist_id'], unique=False)
    # ### end Alembic commands ###
